module.exports = {
    HANDLE_SELCT_YEARS: "[ HANDLE_SELCT_YEARS ]",
    HANDLE_SELCT_TYPE: "[ HANDLE_SELCT_TYPE ]",
    HANDLE_SELECT_REGION: "[ HANDLE_SELECT_REGION ]",
    VN_SEARCH: "[ VN_SEARCH ]",
    CAR_SEARCH: "[CAR_SEARCH]",
    CLEAR_CAR_SEARCH: "[CLEAR_CAR_SEARCH]",
    PNC_SEARCH: "[PNC_SEARCH]",
    PART_SEARCH: "[PART_SEARCH]",
    CLEAR_PART_PNC: "[CLEAR_PART_PNC]",
    PDF_URL:'[PDF_URL]',
    KIA_PNC_SEARCH:'[KIA_PNC_SEARCH]',
    FILTERS_CLEAR:'[FILTERS_CLEAR]'
}